### ISSUE TITLE
TokenRegistry 'unregister' not working

### ISSUE THREAD

**Issue by slothbag** [ethcore/contracts#16]
Hi guys, i've tried to raise this issue several times but it keeps getting closed with little to no feedback..

I'm trying to unregister my token but its modifier only allows the TokenRegister contract owner to call unregister.

https://github.com/ethcore/contracts/blob/master/TokenReg.sol#L49

Is this a bug or is there somewhere I can request a token removal?

**Comment by gavofyork** [comment]
Tokens are not meant to be unregistered; this is to reduce the risk of name squatting by making them a use-once resource only.

If you made a mistake, contact us in gitter and we can help get it removed.
