### ISSUE TITLE
improper use of 'delete' in registry.sol & tokenreg.sol

### ISSUE THREAD

**Issue by KenKappler** [ethcore/contracts#7]
Deleting a struct which contains (for example) a mapping whose size is determined by a user:

```
    struct Token {
        address addr;
        string tla;
        uint base;
        string name;
        address owner;
        mapping (bytes32 => bytes32) meta;
    }

delete tokens[_id];
```

should not be attempted as Token owner can inflate the number of entries in `meta` until there is too much data to be deleted within the gas limit of a block - this would stop the owner from ever deleting the entry.

**Comment by gavofyork** [comment]
i think in this case entries of `meta` are never deleted anyway - so the bug is one of a storage leak rather than inability to delete.

**Comment by slothbag** [comment]
using Parity 1.4.2 I cant delete a token from the TokenRegistry.. the unregister tx succeeds but the token never goes away
